- type: job
  id: USCaptain
  name: job-name-civ-us-cpt
  faction: US
  originalName: Captain
  description: job-description-civ-us-cpt
  playTimeTracker: JobUSCaptain
  requirements:
    - !type:TotalJobsTimeRequirement
      group: CivJobsSquadLeader
      time: 7200 # 2 hours
  startingGear: USCaptainGear
  icon: "JobIconICpt"
  supervisors: job-supervisors-nobody
  ranks:
    RankMajor:
      - !type:RoleTimeRequirement
        role: JobUSCaptain
        time: 18000 # 5 hours
    RankCaptain: []
  special:
    - !type:AddComponentSpecial
      components:
        - type: NpcFactionMember
          factions:
            - US
        - type: ShowFactionIcons
          factionIcon: UsFaction
          jobIcon: JobIconICpt

- type: startingGear
  id: USCaptainGear
  equipment:
    shoes: civ13_shoes_jackboots
    jumpsuit: civ13_uniform_American_captain_uniform
    neck: civ13_accessory_green_PASGT_body_armor
    head: civ13_head_M1_Captain_Helmet
    belt: civ13_pistol_M1911A1
    pocket1: civ13_magazine_M1911_magazine_(.45)
    pocket2: Compass
    ears: ClothingHeadsetUS

# Sergeant

- type: job
  id: USSergeant
  originalName: Sergeant
  name: job-name-civ-us-sgt
  faction: US
  description: job-description-civ-us-sergeant
  playTimeTracker: JobUSSergeant
  requirements:
    - !type:TotalJobsTimeRequirement
      group: CivJobsEnlisted
      time: 7200 # 2 hours
  startingGear: USSergeantGear
  icon: "JobIconISgt"
  supervisors: job-supervisors-cpt
  ranks:
    RankSergeantMajor:
      - !type:RoleTimeRequirement
        role: JobUSSergeant
        time: 36000 # 10 hours
    RankStaffSergeant:
      - !type:RoleTimeRequirement
        role: JobUSSergeant
        time: 10800 # 3 hours
    RankSergeant: []
  special:
    - !type:AddComponentSpecial
      components:
        - type: NpcFactionMember
          factions:
            - US
        - type: ShowFactionIcons
          factionIcon: UsFaction
          jobIcon: JobIconISgt
          assignSquad: true

- type: startingGear
  id: USSergeantGear
  equipment:
    shoes: civ13_shoes_jackboots
    jumpsuit: civ13_uniform_US_Army_Officer_Uniform
    neck: civ13_accessory_woodland_PASGT_body_armor
    head: civ13_head_M1_1st_LT_Helmet
    belt: civ13_pistol_M1911A1
    pocket1: civ13_magazine_M1911_magazine_(.45)
    pocket2: Compass
    ears: ClothingHeadsetUS
  inhand:
    - civ13_ar_M16A2

# Assault Rifleman

- type: job
  id: USRifleman
  name: job-name-civ-us-rifleman
  faction: US
  originalName: Rifleman
  description: job-description-civ-us-rifleman
  playTimeTracker: JobUSRifleman
  startingGear: USRiflemanGear
  randomStartingGears: [USRiflemanGear, USRiflemanGear2]
  icon: "JobIconICpl"
  supervisors: job-supervisors-cpt
  ranks:
    RankLanceCorporal:
      - !type:RoleTimeRequirement
        role: JobUSRifleman
        time: 36000 # 10 hours
    RankPrivateFirstClass:
      - !type:RoleTimeRequirement
        role: JobUSRifleman
        time: 10800 # 3 hours
    RankPrivate: []
  special:
    - !type:AddComponentSpecial
      components:
        - type: NpcFactionMember
          factions:
            - US
        - type: ShowFactionIcons
          factionIcon: UsFaction
          jobIcon: JobIconRifleman
          assignSquad: true

- type: startingGear
  id: USRiflemanGear
  equipment:
    shoes: civ13_shoes_jackboots
    jumpsuit: civ13_uniform_American_uniform
    head: civ13_head_M1_Helmet
    belt: ClothingWebbingUSCWRifleman
    neck: civ13_accessory_woodland_PASGT_body_armor
    pocket1: Gauze
    pocket2: Gauze
    ears: ClothingHeadsetUS
  inhand:
    - civ13_ar_M16A2

- type: startingGear
  id: USRiflemanGear2
  equipment:
    shoes: civ13_shoes_jackboots
    jumpsuit: civ13_uniform_American_uniform
    head: civ13_head_M1_Helmet_with_netting_1
    belt: ClothingWebbingUSCWRifleman
    neck: civ13_accessory_woodland_PASGT_body_armor
    pocket1: Gauze
    pocket2: Gauze
    ears: ClothingHeadsetUS
  inhand:
    - civ13_ar_M16A2

# Machinegunner

- type: job
  id: USMachinegunner
  name: job-name-civ-us-machinegunner
  faction: US
  originalName: Machinegunner
  description: job-description-civ-us-machinegunner
  playTimeTracker: JobUSMachinegunner
  startingGear: USMachinegunnerGear
  randomStartingGears: [USMachinegunnerGear, USMachinegunnerGear2]
  icon: "JobIconMg"
  supervisors: job-supervisors-cpt
  requirements:
    - !type:TotalJobsTimeRequirement
      group: CivJobsEnlisted
      time: 3600 # 1 hours
  ranks:
    RankLanceCorporal:
      - !type:RoleTimeRequirement
        role: JobUSMachinegunner
        time: 36000 # 10 hours
    RankPrivateFirstClass:
      - !type:RoleTimeRequirement
        role: JobUSMachinegunner
        time: 10800 # 3 hours
    RankPrivate: []
  special:
    - !type:AddComponentSpecial
      components:
        - type: NpcFactionMember
          factions:
            - US
        - type: ShowFactionIcons
          factionIcon: UsFaction
          jobIcon: JobIconMg
          assignSquad: true

- type: startingGear
  id: USMachinegunnerGear
  equipment:
    shoes: civ13_shoes_jackboots
    jumpsuit: civ13_uniform_American_uniform
    head: civ13_head_M1_Helmet
    belt: ClothingWebbingUSCWMG
    neck: civ13_accessory_woodland_PASGT_body_armor
    pocket1: CombatKnife
    pocket2: Gauze
    ears: ClothingHeadsetUS
  inhand:
    - civ13_mg_M60

- type: startingGear
  id: USMachinegunnerGear2
  equipment:
    shoes: civ13_shoes_jackboots
    jumpsuit: civ13_uniform_American_uniform
    head: civ13_head_M1_Helmet_with_netting
    belt: ClothingWebbingUSCWMG
    neck: civ13_accessory_woodland_PASGT_body_armor
    pocket1: CombatKnife
    pocket2: Gauze
    ears: ClothingHeadsetUS
  inhand:
    - civ13_mg_M60

# Medic

- type: job
  id: USMedic
  name: job-name-civ-us-medic
  faction: US
  originalName: Medic
  description: job-description-civ-us-medic
  playTimeTracker: JobUSMedic
  startingGear: USMedicGear
  icon: "JobIconMedic"
  supervisors: job-supervisors-cpt
  requirements:
    - !type:TotalJobsTimeRequirement
      group: CivJobsEnlisted
      # time: 9000 # 2.5 hours
      time: 3600 # 1 hour temporarily until people build up playtime
  ranks:
    RankSergeant:
      - !type:RoleTimeRequirement
        role: JobUSMedic
        time: 10800 # 3 hours
    RankCorporal: []
  special:
    - !type:AddComponentSpecial
      components:
        - type: NpcFactionMember
          factions:
            - US
        - type: ShowFactionIcons
          factionIcon: UsFaction
          jobIcon: JobIconMedic

- type: startingGear
  id: USMedicGear
  equipment:
    shoes: civ13_shoes_jackboots
    jumpsuit: civ13_uniform_American_uniform
    head: civ13_head_M1_Medic_Helmet
    belt: ClothingSatchelMedicalMedsFilled
    back: ClothingBackpackDuffelFilled
    neck: civ13_accessory_woodland_PASGT_body_armor
    pocket1: CombatKnife
    ears: ClothingHeadsetUS
  inhand:
    - civ13_ar_M16A2
